title:             一丁顶风跑
email:             yidingdingfengpao@gmail.com
description:       凡是过往，皆为序章。
author:            Brenda Zh
baseurl:           "/yiding_blog"
url:               "http://yidingdingfengpao.github.io"

# Social Profiles
#twitter_username:  SBootstrap
github_username:   yidingdingfengpao
#facebook_username: StartBootstrap

# Build settings
markdown:          kramdown
paginate:          5
paginate_path:     "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
